name: Test switch case

on: [push]
  # pull_request:
  #   types:
  #     - closed

jobs:
  before_script:
    name: check branch
    runs-on: ubuntu-latest
    outputs:
      env-stage: ${{ steps.switch-case.outputs.match }}
    steps:
    - name: Run switch-case-action
      uses: thaitype/actions-switch-case@v1
      id: switch-case
      with:
        default: none
        conditionals-with-values: |
          ${{ github.head_ref == 'main' }} => prod
          ${{ github.head_ref == 'staging' }} => stage
          ${{ github.head_ref == 'develop' }} => dev

  check_output:
    name: check output
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ needs.before_script.outputs.switch-case.outputs.env-stage }}
    # if: ${{ github.event.pull_request.merged }} && !($STAGE == "none")
    steps:
    - run: echo ${{ github.head_ref}}
    - name: check output
      run: echo $STAGE
