name: Test switch case

on: [push]
  # pull_request:
  #   types:
  #     - closed

jobs:
  before_script:
    name: check branch
    runs-on: ubuntu-latest
    outputs:
      env_stage: ${{ steps.switch-case.outputs.test }}
    steps:
    - name: Run switch-case-action
      uses: thaitype/actions-switch-case@v1
      id: switch_case
      with:
        default: none
        conditionals-with-values: |
          ${{ github.ref_name == 'main' }} => prod
          ${{ github.ref_name == 'staging' }} => stage
          ${{ github.ref_name == 'develop' }} => dev
    - run: |
        echo "stage=${{ steps.switch_case.outputs.match }}" >> "$GITHUB_OUTPUT"

  check_output:
    name: check output
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ needs.before_script.outputs.switch_case.outputs.env_stage }}
    # if: ${{ github.event.pull_request.merged }} && !($STAGE == "none")
    steps:
    - run: |
        echo ${{ github.ref_name }}
        echo ${{ needs.before_script.outputs.switch_case.outputs.env_stage }}
    - name: check output
      run: echo $STAGE
